from pprint import pprint

region_codes = {
    '01':'Stockholm',
    '03':'Uppsala',
    '04':'Södermanland',
    '05':'Östergötland',
    '06':'Jönköping',
    '07':'Kronoberg',
    '08':'Kalmar',
    '09':'Gotland',
    '10':'Blekinge',
    '12':'Skåne',
    '13':'Halland',
    '14':'Västra Götaland',
    '17':'Värmland',
    '18':'Örebro',
    '19':'Västmanland',
    '20':'Dalarna',
    '21':'Gävleborg',
    '22':'Västernorrland',
    '23':'Jämtland',
    '24':'Västerbotten',
    '25':'Norrbotten',
    '00': 'Okänd region'
}

codes = [{'Children': [{'Children': [{'Key': '37', 'Value': 'Karlskrona IVA'},
                             {'Key': '87', 'Value': 'Karlskrona TIVA'}],
                'Key': '-18000',
                'Value': 'Blekinge'},
               {'Children': [{'Key': '27', 'Value': 'Falun'},
                             {'Key': '41', 'Value': 'Mora'}],
                'Key': '-5000',
                'Value': 'Dalarna'},
               {'Children': [{'Key': '61', 'Value': 'Visby'}],
                'Key': '-20000',
                'Value': 'Gotland'},
               {'Children': [{'Key': '46', 'Value': 'Bollnäs'},
                             {'Key': '4', 'Value': 'Gävle'},
                             {'Key': '44', 'Value': 'Hudiksvall'}],
                'Key': '-6000',
                'Value': 'Gävleborg'},
               {'Children': [{'Key': '29', 'Value': 'Halmstad'},
                             {'Key': '35', 'Value': 'Varberg'}],
                'Key': '-16000',
                'Value': 'Halland'},
               {'Children': [{'Key': '23', 'Value': 'Östersund'}],
                'Key': '-3000',
                'Value': 'Jämtland'},
               {'Children': [{'Key': '15', 'Value': 'Eksjö'},
                             {'Key': '14', 'Value': 'Jönköping'},
                             {'Key': '16', 'Value': 'Värnamo'}],
                'Key': '-13000',
                'Value': 'Jönköping'},
               {'Children': [{'Key': '1', 'Value': 'Kalmar'},
                             {'Key': '3', 'Value': 'Västervik'}],
                'Key': '-19000',
                'Value': 'Kalmar'},
               {'Children': [{'Key': '49', 'Value': 'Ljungby'},
                             {'Key': '36', 'Value': 'Växjö'}],
                'Key': '-17000',
                'Value': 'Kronoberg'},
               {'Children': [{'Key': '45', 'Value': 'Gällivare'},
                             {'Key': '70', 'Value': 'Kalix'},
                             {'Key': '68', 'Value': 'Piteå'},
                             {'Key': '48', 'Value': 'Sunderby'}],
                'Key': '-1000',
                'Value': 'Norrbotten'},
               {'Children': [{'Key': '54', 'Value': 'Helsingborg'},
                             {'Key': '10', 'Value': 'Kristianstad'},
                             {'Key': '73', 'Value': 'SUS Lund BIVA'},
                             {'Key': '30', 'Value': 'SUS Lund IVA'},
                             {'Key': '74', 'Value': 'SUS Lund NIVA'},
                             {'Key': '75', 'Value': 'SUS Lund TIVA'},
                             {'Key': '88', 'Value': 'SUS Malmö Inf'},
                             {'Key': '24', 'Value': 'SUS Malmö IVA'},
                             {'Key': '53', 'Value': 'Ystad'}],
                'Key': '-21000',
                'Value': 'Skåne'},
               {'Children': [{'Key': '6', 'Value': 'Danderyd'},
                             {'Key': '43', 'Value': 'Ersta'},
                             {'Key': '62', 'Value': 'K Huddinge IVA'},
                             {'Key': '72', 'Value': 'K Solna BIVA'},
                             {'Key': '95', 'Value': 'K Solna ECMO'},
                             {'Key': '42', 'Value': 'K Solna IVA'},
                             {'Key': '77', 'Value': 'K Solna NIVA'},
                             {'Key': '9', 'Value': 'K Solna TIVA'},
                             {'Key': '8', 'Value': 'Norrtälje'},
                             {'Key': '7', 'Value': 'St Göran'},
                             {'Key': '58', 'Value': 'Södertälje'},
                             {'Key': '5', 'Value': 'SÖS IVA'},
                             {'Key': '89', 'Value': 'SÖS MIVA'}],
                'Key': '-11000',
                'Value': 'Stockholm'},
               {'Children': [{'Key': '64', 'Value': 'Eskilstuna'},
                             {'Key': '57', 'Value': 'Nyköping'}],
                'Key': '-15000',
                'Value': 'Sörmland'},
               {'Children': [{'Key': '55', 'Value': 'Uppsala BIVA'},
                             {'Key': '90', 'Value': 'Uppsala BRIVA'},
                             {'Key': '56', 'Value': 'Uppsala CIVA'},
                             {'Key': '79', 'Value': 'Uppsala NIVA'},
                             {'Key': '78', 'Value': 'Uppsala TIVA'}],
                'Key': '-10000',
                'Value': 'Uppsala'},
               {'Children': [{'Key': '39', 'Value': 'Alingsås'},
                             {'Key': '28', 'Value': 'Borås'},
                             {'Key': '52', 'Value': 'Kungälv'},
                             {'Key': '34', 'Value': 'Lidköping'},
                             {'Key': '92', 'Value': 'NU Trollhättan'},
                             {'Key': '31', 'Value': 'NÄL'},
                             {'Key': '33', 'Value': 'Skövde'},
                             {'Key': '59', 'Value': 'SU BIVA'},
                             {'Key': '19', 'Value': 'SU CIVA'},
                             {'Key': '22', 'Value': 'SU Mölndal'},
                             {'Key': '20', 'Value': 'SU NIVA'},
                             {'Key': '18', 'Value': 'SU TIVA'},
                             {'Key': '21', 'Value': 'SU Östra'},
                             {'Key': '86', 'Value': 'SU Östra Inf'},
                             {'Key': '38', 'Value': 'Uddevalla'}],
                'Key': '-12000',
                'Value': 'V. Götaland'},
               {'Children': [{'Key': '25', 'Value': 'Arvika'},
                             {'Key': '17', 'Value': 'Karlstad'},
                             {'Key': '26', 'Value': 'Torsby'}],
                'Key': '-7000',
                'Value': 'Värmland'},
               {'Children': [{'Key': '71', 'Value': 'Lycksele'},
                             {'Key': '51', 'Value': 'Skellefteå'},
                             {'Key': '47', 'Value': 'Umeå IVA'},
                             {'Key': '81', 'Value': 'Umeå TIVA'}],
                'Key': '-2000',
                'Value': 'Västerbotten'},
               {'Children': [{'Key': '32', 'Value': 'Sollefteå'},
                             {'Key': '66', 'Value': 'Sundsvall'},
                             {'Key': '67', 'Value': 'Örnsköldsvik'}],
                'Key': '-4000',
                'Value': 'Västernorrland'},
               {'Children': [{'Key': '65', 'Value': 'Västerås'}],
                'Key': '-9000',
                'Value': 'Västmanland'},
               {'Children': [{'Key': '84', 'Value': 'Karlskoga'},
                             {'Key': '85', 'Value': 'Lindesberg'},
                             {'Key': '50', 'Value': 'Örebro IVA'},
                             {'Key': '83', 'Value': 'Örebro TIVA'}],
                'Key': '-8000',
                'Value': 'Örebro'},
               {'Children': [{'Key': '91', 'Value': 'Linköping BRIVA'},
                             {'Key': '11', 'Value': 'Linköping IVA'},
                             {'Key': '82', 'Value': 'Linköping NIVA'},
                             {'Key': '40', 'Value': 'Linköping TIVA'},
                             {'Key': '12', 'Value': 'Norrköping'}],
                'Key': '-14000',
                'Value': 'Östergötland'}],
  'Key': '-999',
  'Value': 'Alla avdelningar'}]

def search_region(text):
    text = text.lower()

    for region_key, region_name in region_codes.items():

        if region_name.lower() in text:
            return region_key


    return '00'

hc = {}

for code in codes[0]['Children']:
    region_name = code['Value']
    sub_hospitals = []

    for h in code['Children']:
        sub_hospitals.append(h['Key'])

    hc[region_name] = sub_hospitals

pprint(hc)
