# Generated by Django 3.0.4 on 2020-03-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronacase',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
