# Generated by Django 3.0.4 on 2020-03-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_coronacase_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coronacase',
            old_name='location',
            new_name='region',
        ),
    ]
