# Generated by Django 3.0.4 on 2020-03-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004_auto_20200309_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronacase',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
