# Generated by Django 3.0.4 on 2020-03-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0005_coronacase_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronacase',
            name='backup',
            field=models.BooleanField(default=True),
        ),
    ]
