# Generated by Django 3.0.4 on 2020-03-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0007_scrapesite'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapesite',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
