# Generated by Django 3.0.4 on 2020-03-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0009_prognosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronacase',
            name='case_type',
            field=models.CharField(default='confirmed', max_length=255),
        ),
    ]
