# Generated by Django 3.0.4 on 2020-03-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0010_coronacase_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronacase',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insight.ScrapeSite'),
        ),
    ]
