# Generated by Django 3.0.4 on 2020-03-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0011_coronacase_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapesite',
            name='verbose_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
