# Generated by Django 3.0.4 on 2020-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0012_scrapesite_verbose_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('infected', models.IntegerField(default=0)),
                ('dead', models.IntegerField(default=0)),
            ],
        ),
    ]
