# Generated by Django 3.0.4 on 2020-03-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0014_auto_20200314_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrytracker',
            old_name='dead',
            new_name='new_deaths',
        ),
        migrations.AddField(
            model_name='countrytracker',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
    ]
