# Generated by Django 3.0.4 on 2020-03-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0015_auto_20200314_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrytracker',
            old_name='new_infected',
            new_name='new_cases',
        ),
        migrations.RenameField(
            model_name='countrytracker',
            old_name='total_infected',
            new_name='total_cases',
        ),
    ]
