# Generated by Django 3.0.4 on 2020-03-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0017_article_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
