# Generated by Django 3.0.4 on 2020-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0021_auto_20200325_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronacase',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
