# Generated by Django 3.0.4 on 2020-03-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0022_coronacase_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytracker',
            name='in_hospital',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='countrytracker',
            name='in_intensive_care',
            field=models.IntegerField(default=0),
        ),
    ]
